Repository pshenmic/platform-explorer, pull requests merged in 2024-11, with the labels that each got.

#303 Upgrade to Dash Platform v1.5.1
  packages/api/package.json
  packages/data-contract/package.json
  packages/indexer/Cargo.lock
  packages/indexer/Cargo.toml
  packages/indexer/Dockerfile
  packages/indexer/src/entities/identity.rs
Labels: Indexer, backend

#298 Implement date range picker in validator proposed blocks chart
  packages/frontend/src/app/validator/[hash]/BlocksChart.js
  packages/frontend/src/app/validator/[hash]/TabsChart.scss
  packages/frontend/src/app/validator/[hash]/Validator.js
  packages/frontend/src/app/validator/[hash]/ValidatorPage.scss
  packages/frontend/src/components/calendar/DateRangePicker.js
  packages/frontend/src/components/calendar/DateRangePicker.scss
  packages/frontend/src/components/cards/ValueCard.scss
  packages/frontend/src/components/charts/ChartBlock.scss
  packages/frontend/src/components/charts/LineChartBlock.js
  packages/frontend/src/components/charts/TimeframeMenu.js
  packages/frontend/src/components/charts/TimeframeMenu.scss
  packages/frontend/src/components/charts/TimeframeSelector.js
  packages/frontend/src/components/charts/TimeframeSelector.scss
  packages/frontend/src/components/charts/TransactionsHistory.js
  packages/frontend/src/components/charts/charts.scss
  packages/frontend/src/components/charts/index.js
  packages/frontend/src/components/data/CreditsBlock.scss
  packages/frontend/src/components/data/Endpoint.js
  packages/frontend/src/components/dataContracts/DataContractCard.scss
  packages/frontend/src/components/documents/DocumentsListItem.scss
  packages/frontend/src/components/imageGenerator/index.js
  packages/frontend/src/components/layout/footer/footer.scss
  packages/frontend/src/components/layout/footer/index.js
  packages/frontend/src/components/layout/navbar/NavLink.scss
  packages/frontend/src/components/layout/navbar/Navbar.scss
  packages/frontend/src/components/layout/navbar/NetworkSelect.scss
  packages/frontend/src/components/networkStatus/NetworkStatus.scss
  packages/frontend/src/components/total/TotalInfoItem.scss
  packages/frontend/src/components/total/ValueBlock.scss
  packages/frontend/src/components/transactions/TransactionsListItem.scss
  packages/frontend/src/components/transfers/TransfersListItem.scss
  packages/frontend/src/components/ui/NavigationButton/NavigationButton.scss
  packages/frontend/src/components/ui/containers/InfoContainer.scss
  packages/frontend/src/components/ui/containers/PageDataContainer.js
  packages/frontend/src/components/ui/containers/ValueContainer.js
  packages/frontend/src/components/ui/containers/ValueContainer.scss
  packages/frontend/src/components/ui/icons/index.js
  packages/frontend/src/components/ui/lists/SimpleList.scss
  packages/frontend/src/components/validators/ValidatorCard.scss
  packages/frontend/src/components/validators/ValidatorListItem.scss
  packages/frontend/src/styles/components/InfoBlock.scss
  packages/frontend/src/styles/components/Tabs.js
  packages/frontend/src/styles/components/TabsChart.scss
  packages/frontend/src/styles/mixins.scss
  packages/frontend/src/styles/theme.js
  packages/frontend/src/styles/theme.scss
  packages/frontend/src/util/Api.js
  packages/frontend/src/util/datetime.js
  packages/frontend/src/util/index.js
Labels: frontend

#297 Incorrect timeout error
  packages/api/src/utils.js
Labels: backend

#306 Aliases with ContestedResourceVoteState
  packages/api/README.md
  packages/api/package.json
  packages/api/src/DAPI.js
  packages/api/src/constants.js
  packages/api/src/controllers/IdentitiesController.js
  packages/api/src/controllers/MainController.js
  packages/api/src/controllers/TransactionsController.js
  packages/api/src/dao/IdentitiesDAO.js
  packages/api/src/dao/TransactionsDAO.js
  packages/api/src/models/Identity.js
  packages/api/src/models/Transaction.js
  packages/api/src/routes.js
  packages/api/src/server.js
  packages/api/src/utils.js
  packages/api/test/integration/identities.spec.js
  packages/api/test/integration/main.spec.js
  packages/api/test/integration/transactions.spec.js
  packages/frontend/src/app/api/content.md
Labels: backend

#314 Rollback to the previous dapi client initialization method
  packages/api/src/server.js
Labels: backend

#315 Update alias display for new format
  packages/frontend/src/app/home/Home.js
  packages/frontend/src/app/identity/[identifier]/Identity.js
  packages/frontend/src/components/data/Alias.js
  packages/frontend/src/components/identities/Cards.js
  packages/frontend/src/components/identities/IdentitiesListItem.js
Labels: frontend

#316 Add support for old alias format
  packages/frontend/src/app/home/Home.js
  packages/frontend/src/app/identity/[identifier]/Identity.js
  packages/frontend/src/components/identities/Cards.js
  packages/frontend/src/components/identities/IdentitiesListItem.js
Labels: frontend

#317 API container paths fix
  packages/api/Dockerfile
Labels: backend

#312 Expanding decoding response for transactions
  packages/api/.env
  packages/api/README.md
  packages/api/package.json
  packages/api/src/DAPI.js
  packages/api/src/constants.js
  packages/api/src/controllers/IdentitiesController.js
  packages/api/src/dao/TransactionsDAO.js
  packages/api/src/enums/DocumentActionEnum.js
  packages/api/src/enums/PoolingEnum.js
  packages/api/src/utils.js
  packages/api/test/integration/identities.spec.js
  packages/api/test/unit/utils.spec.js
  packages/frontend/src/app/api/content.md
Labels: backend

#329 Implement Tables in Markdown
  packages/frontend/package.json
  packages/frontend/src/components/markdown/Markdown.scss
  packages/frontend/src/components/markdown/index.js
Labels: frontend

#330 AssetLockProof structure improvments
  packages/api/README.md
  packages/api/src/utils.js
  packages/api/test/unit/utils.spec.js
  packages/frontend/src/app/api/content.md
Labels: backend

#331 Public Keys Structure Improvments
  packages/api/README.md
  packages/api/src/enums/KeyPurposeEnum.js
  packages/api/src/enums/KeyTypeEnum.js
  packages/api/src/enums/SecurityLevelEnum.js
  packages/api/src/utils.js
  packages/api/test/unit/utils.spec.js
  packages/frontend/src/app/api/content.md
Labels: backend

#305 Update transactions page
  packages/frontend/src/app/block/[hash]/Block.js
  packages/frontend/src/app/home/Home.js
  packages/frontend/src/app/identity/[identifier]/Identity.js
  packages/frontend/src/app/transactions/Transactions.js
  packages/frontend/src/components/transactions/StatusIcon.js
  packages/frontend/src/components/transactions/TransactionsList.js
  packages/frontend/src/components/transactions/TransactionsList.scss
  packages/frontend/src/components/transactions/TransactionsListItem.js
  packages/frontend/src/components/transactions/TransactionsListItem.scss
  packages/frontend/src/components/transactions/TypeBadge.js
  packages/frontend/src/components/transactions/_variables.scss
  packages/frontend/src/components/ui/Tooltips/RateTooltip.js
  packages/frontend/src/components/ui/icons/index.js
Labels: frontend

#332 Withdrawals output address and document id field
  packages/api/README.md
  packages/api/src/controllers/IdentitiesController.js
  packages/api/src/dao/IdentitiesDAO.js
  packages/api/src/server.js
  packages/api/src/utils.js
  packages/api/test/integration/identities.spec.js
  packages/frontend/src/app/api/content.md
Labels: backend

#307 Implement a list of withdrawals on the validator page
  packages/frontend/src/app/validator/[hash]/Validator.js
  packages/frontend/src/components/transfers/TransfersList.js
  packages/frontend/src/components/transfers/index.js
  packages/frontend/src/components/transfers/withdrawals/StatusIcon.js
  packages/frontend/src/components/transfers/withdrawals/WithdrawalsList.js
  packages/frontend/src/components/transfers/withdrawals/WithdrawalsList.scss
  packages/frontend/src/components/transfers/withdrawals/WithdrawalsListItem.js
  packages/frontend/src/components/transfers/withdrawals/WithdrawalsListItem.scss
  packages/frontend/src/components/transfers/withdrawals/_variables.scss
  packages/frontend/src/components/ui/containers/ValueContainer.js
  packages/frontend/src/components/ui/containers/ValueContainer.scss
  packages/frontend/src/styles/mixins.scss
Labels: frontend

#334 Frontend bug fix
  packages/frontend/src/components/networkStatus/index.js
  packages/frontend/src/components/transactions/TransactionsListItem.scss
Labels: frontend

#335 Aliases status fix
  packages/api/src/dao/IdentitiesDAO.js
Labels: backend

#346 Target branch rule for lint action
  .github/workflows/build.yml
  .github/workflows/deploy.yml
Labels: enhancement, data contract, Indexer, backend, design

#348 Validator By Identity Endpoint
  packages/api/README.md
  packages/api/src/controllers/ValidatorsController.js
  packages/api/src/routes.js
  packages/api/test/integration/validators.spec.js
  packages/frontend/src/app/api/content.md
Labels: backend

#321 Transactions filters
  packages/api/README.md
  packages/api/src/controllers/TransactionsController.js
  packages/api/src/dao/TransactionsDAO.js
  packages/api/src/schemas.js
  packages/api/test/integration/transactions.spec.js
  packages/frontend/src/app/api/content.md
Labels: backend
