Repository pshenmic/platform-explorer, pull requests merged in 2024-09, with the labels that each got.

#240 Removed case sensitivity for hash
  packages/api/src/dao/BlocksDAO.js
  packages/api/src/dao/TransactionsDAO.js
  packages/api/src/dao/ValidatorsDAO.js
  packages/api/src/routes.js
Labels: backend

#244 Update network selector
  packages/frontend/.env
  packages/frontend/src/components/layout/navbar/Dropdown.js
  packages/frontend/src/components/layout/navbar/NetworkSelect.js
  packages/frontend/src/components/layout/navbar/NetworkSelect.scss
  packages/frontend/src/components/ui/NavigationButton/NavigationButton.js
  packages/frontend/src/components/ui/NavigationButton/NavigationButton.scss
  packages/frontend/src/util/Api.js
Labels: frontend

#227 Fetch Identity balance from DAPI GRPC
  .github/workflows/build.yml
  packages/api/.env
  packages/api/src/controllers/IdentitiesController.js
  packages/api/src/controllers/MainController.js
  packages/api/src/dao/IdentitiesDAO.js
  packages/api/src/dapi.js
  packages/api/src/schemas.js
  packages/api/src/server.js
  packages/api/test/integration/identities.spec.js
  packages/api/test/integration/main.spec.js
Labels: backend

#224 Add platform total credits API in the status
  packages/api/.env
  packages/api/README.md
  packages/api/src/controllers/MainController.js
  packages/api/src/dapi.js
  packages/api/src/server.js
  packages/api/test/integration/main.spec.js
  packages/frontend/src/app/api/content.md
Labels: backend

#245 Fix for default dapi address
  packages/api/src/server.js
Labels: backend

#248 Update validators list filter
  packages/frontend/src/app/validators/Validators.js
  packages/frontend/src/util/Api.js
Labels: frontend

#249 Add validator's identities in the indexer
  packages/indexer/Cargo.lock
  packages/indexer/Cargo.toml
  packages/indexer/src/entities/identity.rs
  packages/indexer/src/processor/psql/dao/mod.rs
  packages/indexer/src/processor/psql/mod.rs
Labels: Indexer

#243 Improve mobile menu
  packages/frontend/src/components/layout/Background.scss
  packages/frontend/src/components/layout/navbar/NavLink.scss
  packages/frontend/src/components/layout/navbar/Navbar.js
  packages/frontend/src/components/layout/navbar/Navbar.scss
  packages/frontend/src/components/layout/navbar/NavbarMobileMenu.scss
Labels: frontend

#250 Query epoch from DAPI
  packages/api/Dockerfile
  packages/api/README.md
  packages/api/package.json
  packages/api/src/DAPI.js
  packages/api/src/controllers/EpochController.js
  packages/api/src/controllers/MainController.js
  packages/api/src/dao/EpochDAO.js
  packages/api/src/models/Epoch.js
  packages/api/src/server.js
  packages/api/test/integration/epochs.spec.js
  packages/api/test/integration/identities.spec.js
  packages/api/test/integration/main.spec.js
  packages/api/test/unit/models/Epoch.spec.js
  packages/frontend/src/app/api/content.md
Labels: backend

#252 Revert base64 check for masternode identities
  packages/indexer/src/processor/psql/dao/mod.rs
Labels: Indexer

#254 Identity field for Validators
  packages/api/README.md
  packages/api/package.json
  packages/api/src/controllers/ValidatorsController.js
  packages/api/src/models/Validator.js
  packages/api/test/integration/validators.spec.js
  packages/frontend/src/app/api/content.md
Labels: backend

#247 Implement new data on frontend
  packages/frontend/src/app/dataContract/[identifier]/DataContract.js
  packages/frontend/src/app/validator/[hash]/Validator.js
  packages/frontend/src/app/validators/page.js
  packages/frontend/src/components/blocks/BlocksTotal.js
  packages/frontend/src/components/networkStatus/index.js
  packages/frontend/src/components/total/TotalCards.js
  packages/frontend/src/components/validators/ValidatorsList.scss
  packages/frontend/src/components/validators/ValidatorsTotal.js
  packages/frontend/src/util/Api.js
Labels: frontend

#263 Upgrade to platform v1.3.0
  packages/api/package.json
  packages/data-contract/package.json
  packages/indexer/Cargo.lock
  packages/indexer/Dockerfile
Labels: Indexer, backend

#256 Auto publish release
  .github/workflows/release.yml
Labels: data contract, Indexer, frontend, backend

#253 Case sensitivity in search
  packages/api/src/controllers/MainController.js
Labels: backend

#255 Tests for epochs
  packages/api/src/controllers/EpochController.js
  packages/api/test/integration/epochs.spec.js
Labels: backend

#258 Default value for epoch on Tenderdash error in /status
  packages/api/src/controllers/MainController.js
Labels: backend

#257 Identities sort by balance test fix
  packages/api/test/integration/identities.spec.js
Labels: backend

#260 Total collected fees in the past day
  packages/api/README.md
  packages/api/src/controllers/MainController.js
  packages/api/src/dao/TransactionsDAO.js
  packages/api/test/integration/main.spec.js
  packages/frontend/src/app/api/content.md
Labels: backend

#266 Fix state switch handler in validators list
  packages/frontend/src/app/validators/Validators.js
Labels: frontend

#261 USD rate
  packages/api/README.md
  packages/api/src/coinbase.js
  packages/api/src/controllers/RateController.js
  packages/api/src/kucoin.js
  packages/api/src/routes.js
  packages/api/src/server.js
  packages/frontend/src/app/api/content.md
Labels: backend
