Repository pshenmic/platform-explorer, pull requests merged in 2024-10, with the labels that each got.

#269 Redesign common elements
  packages/frontend/public/images/icons/chevron-right.svg
  packages/frontend/src/app/dataContracts/DataContracts.js
  packages/frontend/src/app/dataContracts/page.js
  packages/frontend/src/app/home/Home.js
  packages/frontend/src/app/home/HomeIntro.scss
  packages/frontend/src/app/transaction/[hash]/Transaction.js
  packages/frontend/src/components/blocks/BlocksListItem.js
  packages/frontend/src/components/blocks/BlocksListItem.scss
  packages/frontend/src/components/cards/CardsGrid.scss
  packages/frontend/src/components/data/Credits.js
  packages/frontend/src/components/data/Credits.scss
  packages/frontend/src/components/data/Identifier.js
  packages/frontend/src/components/data/Identifier.scss
  packages/frontend/src/components/data/index.js
  packages/frontend/src/components/dataContracts/TrendingDataContracts.js
  packages/frontend/src/components/dataContracts/index.js
  packages/frontend/src/components/identities/RichList.js
  packages/frontend/src/components/identities/index.js
  packages/frontend/src/components/layout/navbar/NavLink.scss
  packages/frontend/src/components/total/TotalInfo.js
  packages/frontend/src/components/total/TotalInfoItem.scss
  packages/frontend/src/components/transactions/TransactionsListItem.js
  packages/frontend/src/components/ui/Buttons/CopyButton.js
  packages/frontend/src/components/ui/lists/index.js
  packages/frontend/src/components/validators/ValidatorsList.js
  packages/frontend/src/components/validators/ValidatorsTotal.js
  packages/frontend/src/styles/components/InfoBlock.scss
  packages/frontend/src/styles/mixins.scss
  packages/frontend/src/styles/theme.js
Labels: frontend

#270 Implement document transfers & purchases in the indexer
  packages/indexer/migrations/V42__add_document_price.sql
  packages/indexer/src/entities/document.rs
  packages/indexer/src/processor/psql/dao/mod.rs
  packages/indexer/src/processor/psql/mod.rs
Labels: Indexer

#274 Upgrade to Dash Platform v1.4.0
  .github/workflows/deploy.yml
  packages/api/package.json
  packages/api/test/utils/drop.js
  packages/data-contract/package.json
  packages/indexer/Cargo.lock
  packages/indexer/Dockerfile
Labels: Indexer, backend

#262 Implement new tooltip on the frontend
  packages/frontend/src/app/home/Home.js
  packages/frontend/src/app/identity/[identifier]/Identity.js
  packages/frontend/src/app/transaction/[hash]/Transaction.js
  packages/frontend/src/components/data/Credits.js
  packages/frontend/src/components/dataContracts/DataContractCard.scss
  packages/frontend/src/components/identities/Cards.js
  packages/frontend/src/components/identities/IdentityCard.scss
  packages/frontend/src/components/identities/TopIdentities.js
  packages/frontend/src/components/networkStatus/NetworkStatus.scss
  packages/frontend/src/components/networkStatus/index.js
  packages/frontend/src/components/total/TotalInfoItem.scss
  packages/frontend/src/components/transactions/TransactionsListItem.js
  packages/frontend/src/components/transactions/TypeBadge.js
  packages/frontend/src/components/ui/Buttons/CopyButton.js
  packages/frontend/src/components/ui/Tooltips/EpochTooltip.js
  packages/frontend/src/components/ui/Tooltips/EpochTooltip.scss
  packages/frontend/src/components/ui/Tooltips/RateTooltip.js
  packages/frontend/src/components/ui/Tooltips/RateTooltip.scss
  packages/frontend/src/components/ui/Tooltips/Tooltip.js
  packages/frontend/src/components/ui/Tooltips/Tooltip.scss
  packages/frontend/src/components/ui/Tooltips/index.js
  packages/frontend/src/components/ui/lists/index.js
  packages/frontend/src/components/validators/ValidatorsTotal.js
  packages/frontend/src/components/validators/ValidatorsTotalCard.scss
  packages/frontend/src/enums/state.transition.type.js
  packages/frontend/src/styles/mixins.scss
  packages/frontend/src/styles/theme.js
  packages/frontend/src/util/Api.js
  packages/frontend/src/util/index.js
Labels: frontend

#271 Transaction error decoding
  packages/api/package.json
  packages/api/src/models/Transaction.js
  packages/api/test/integration/transactions.spec.js
Labels: backend

#276 Transitions decode error: `Cannot deserialize`
  packages/api/package.json
  packages/api/src/server.js
Labels: backend

#275 Kucoin API update
  packages/api/src/kucoin.js
Labels: backend

#277 Deploy action syntax fix
  .github/workflows/deploy.yml
Labels: Indexer, frontend, backend

#278 Implement identities names on the backend
  packages/api/README.md
  packages/api/src/dao/IdentitiesDAO.js
  packages/api/src/models/Identity.js
  packages/api/test/integration/identities.spec.js
  packages/api/test/integration/main.spec.js
  packages/frontend/src/app/api/content.md
Labels: backend

#281 Prefix version and remove unnecessary packages
  packages/api/package.json
Labels: backend

#280 Identities duplicates fix
  packages/api/README.md
  packages/api/src/dao/IdentitiesDAO.js
  packages/api/src/models/Identity.js
  packages/api/test/integration/identities.spec.js
  packages/api/test/integration/main.spec.js
  packages/frontend/src/app/api/content.md
Labels: backend

#264 Validators endpoint: `all` flag
  packages/api/README.md
  packages/api/src/controllers/BlocksController.js
  packages/api/src/controllers/DataContractsController.js
  packages/api/src/controllers/DocumentsController.js
  packages/api/src/controllers/IdentitiesController.js
  packages/api/src/controllers/TransactionsController.js
  packages/api/src/controllers/ValidatorsController.js
  packages/api/src/dao/ValidatorsDAO.js
  packages/api/src/schemas.js
  packages/api/test/integration/validators.spec.js
  packages/frontend/src/app/api/content.md
Labels: backend

#282 Upgrade to Dash Platform v1.4.1
  packages/api/package.json
  packages/data-contract/package.json
  packages/frontend/.env
  packages/indexer/Cargo.lock
  packages/indexer/Dockerfile
Labels: Indexer, backend

#283 Returning dapi-client package and new source for dpp
  packages/api/package.json
  packages/api/src/DAPI.js
  packages/api/src/models/Transaction.js
  packages/api/src/server.js
Labels: backend

#284 Fix NPM dash in the data contracts package
  packages/data-contract/package.json
Labels: data contract

#285 Fix for null TCP_CONNECT_TIMEOUT
  packages/api/src/controllers/ValidatorsController.js
Labels: backend

#286 Rename validators field from `identifier` to `identity`
  packages/api/README.md
  packages/api/src/models/Validator.js
  packages/api/src/models/Witdrawal.js
  packages/api/test/integration/validators.spec.js
  packages/frontend/src/app/api/content.md
Labels: backend

#287 Move endpoints out of protx in the validators
  packages/api/README.md
  packages/api/src/controllers/ValidatorsController.js
  packages/api/src/models/Validator.js
  packages/api/test/integration/validators.spec.js
  packages/frontend/src/app/api/content.md
Labels: backend

#288 Validators structure fix
  packages/api/README.md
  packages/api/src/controllers/ValidatorsController.js
  packages/api/src/utils.js
  packages/api/test/integration/validators.spec.js
  packages/frontend/src/app/api/content.md
Labels: backend

#267 Any range statistics for graphs
  packages/api/README.md
  packages/api/src/controllers/TransactionsController.js
  packages/api/src/controllers/ValidatorsController.js
  packages/api/src/dao/TransactionsDAO.js
  packages/api/src/dao/ValidatorsDAO.js
  packages/api/src/routes.js
  packages/api/src/schemas.js
  packages/api/src/utils.js
  packages/api/test/integration/transactions.spec.js
  packages/api/test/integration/validators.spec.js
Labels: backend

#289 Fix platform node id reference
  packages/frontend/src/components/validators/ValidatorCard.js
Labels: frontend

#290 Decode error with null `outputScript`
  packages/api/src/utils.js
Labels: backend

#291 Fix for search query
  packages/api/src/controllers/MainController.js
  packages/api/src/dao/IdentitiesDAO.js
Labels: backend

#295 Implement "All" option for items on page selector in the validators list
  packages/frontend/src/app/validators/Validators.js
  packages/frontend/src/components/pageSizeSelector/PageSizeSelector.scss
  packages/frontend/src/components/validators/ValidatorsList.js
Labels: frontend

#294 Update the render endpoint error state
  packages/frontend/src/components/data/Endpoint.js
Labels: frontend

#296 Update Validator page
  packages/frontend/src/app/validator/[hash]/Validator.js
  packages/frontend/src/components/blocks/BlocksList.js
  packages/frontend/src/components/blocks/BlocksList.scss
Labels: frontend

#293 Fix network selector
  packages/frontend/src/app/validator/[hash]/Validator.js
  packages/frontend/src/components/layout/navbar/Dropdown.js
  packages/frontend/src/components/layout/navbar/Navbar.js
  packages/frontend/src/components/layout/navbar/NetworkSelect.js
  packages/frontend/src/constants/networks.js
Labels: frontend
