Repository pshenmic/platform-explorer, pull requests merged in 2025-03, with the labels that each got.

#504 SDK Version bump
  packages/api/package.json
Labels: backend

#502 Search route improvements
  packages/api/README.md
  packages/api/src/controllers/MainController.js
  packages/api/src/dao/IdentitiesDAO.js
  packages/api/test/integration/identities.spec.js
  packages/api/test/integration/main.spec.js
  packages/frontend/src/app/api/content.md
Labels: backend

#496 Make creation date clickable
  packages/frontend/src/components/dataContracts/DataContractTotalCard.js
  packages/frontend/src/components/identities/IdentityTotalCard.js
  packages/frontend/src/components/ui/containers/ValueContainer.js
Labels: frontend

#505 Broadcast transaction and identity nonce queries
  packages/api/README.md
  packages/api/package.json
  packages/api/src/DAPI.js
  packages/api/src/controllers/IdentitiesController.js
  packages/api/src/controllers/TransactionsController.js
  packages/api/src/routes.js
  packages/api/src/utils.js
  packages/api/test/integration/documents.spec.js
  packages/api/test/integration/main.spec.js
  packages/api/test/unit/utils.spec.js
  packages/frontend/src/app/api/content.md
Labels: backend

#506 Implement BigInt conversions after #505 PR
  packages/api/src/controllers/MainController.js
  packages/api/src/dao/IdentitiesDAO.js
  packages/api/src/models/Epoch.js
  packages/api/test/integration/epochs.spec.js
  packages/api/test/integration/identities.spec.js
  packages/api/test/integration/main.spec.js
Labels: backend

#507 Fix BigInt for identity balance
  packages/api/src/controllers/ValidatorsController.js
  packages/api/src/dao/IdentitiesDAO.js
  packages/api/test/integration/validators.spec.js
Labels: backend

#508 Add raw public key to identity
  packages/api/src/dao/IdentitiesDAO.js
Labels: backend

#510 Raw documents by identifier from DAPI
  packages/api/README.md
  packages/api/src/DAPI.js
  packages/api/src/controllers/DocumentsController.js
  packages/api/src/routes.js
  packages/frontend/src/app/api/content.md
Labels: backend

#511 Raw data contract by identifier from DAPI
  packages/api/README.md
  packages/api/src/controllers/DataContractsController.js
  packages/api/src/controllers/DocumentsController.js
  packages/api/src/routes.js
  packages/frontend/src/app/api/content.md
Labels: backend

#513 Fix documents raw buffer
  packages/api/src/DAPI.js
  packages/api/src/controllers/DocumentsController.js
Labels: backend

#503 Api power for masternode votes
  packages/api/README.md
  packages/api/src/dao/ContestedResourcesDAO.js
  packages/api/src/dao/MasternodeVotesDAO.js
  packages/api/src/models/Vote.js
  packages/api/src/schemas.js
  packages/api/test/integration/contested.spec.js
  packages/api/test/integration/votes.spec.js
  packages/frontend/src/app/api/content.md
Labels: backend

#500 Statistics for graphs query optimization
  packages/api/README.md
  packages/api/src/controllers/ValidatorsController.js
  packages/api/src/dao/TransactionsDAO.js
  packages/api/src/dao/ValidatorsDAO.js
  packages/api/test/integration/transactions.spec.js
  packages/frontend/src/app/api/content.md
Labels: backend

#512 Update render of new format fields
  packages/frontend/src/app/transaction/[hash]/TransactionData.js
  packages/frontend/src/components/blocks/BlockDigestCard.js
  packages/frontend/src/components/data/CreditsBlock.js
  packages/frontend/src/components/dataContracts/DataContractDigestCard.js
  packages/frontend/src/components/identities/IdentityTotalCard.js
  packages/frontend/src/components/transactions/TransitionCard.js
  packages/frontend/src/components/validators/ValidatorCard.js
Labels: frontend

#515 Search Block field renamed to Blocks in response
  packages/api/README.md
  packages/api/src/controllers/MainController.js
  packages/api/src/dao/TransactionsDAO.js
  packages/api/test/integration/main.spec.js
  packages/api/test/integration/transactions.spec.js
  packages/frontend/src/app/api/content.md
Labels: backend

#490 Update data points count in charts
  packages/frontend/src/components/charts/TimeframeMenu.js
  packages/frontend/src/components/charts/config.js
  packages/frontend/src/components/charts/index.js
Labels: frontend

#516 Fixes for search response and new fields for search response
  packages/api/src/DAPI.js
  packages/api/src/controllers/MainController.js
  packages/api/src/controllers/ValidatorsController.js
  packages/api/src/dao/ValidatorsDAO.js
  packages/api/src/models/Validator.js
  packages/api/test/integration/main.spec.js
Labels: backend

#497 Improve global search
  packages/frontend/src/components/breadcrumbs/Breadcrumbs.js
  packages/frontend/src/components/layout/navbar/Navbar.js
  packages/frontend/src/components/layout/navbar/Navbar.scss
  packages/frontend/src/components/layout/navbar/NetworkSelect.js
  packages/frontend/src/components/layout/navbar/NetworkSelect.scss
  packages/frontend/src/components/loading/LoadingLine.scss
  packages/frontend/src/components/loading/index.js
  packages/frontend/src/components/search/GlobalSearchInput.js
  packages/frontend/src/components/search/SearchResultsList.js
  packages/frontend/src/components/search/SearchResultsList.scss
  packages/frontend/src/components/search/SearchResultsListItem.js
  packages/frontend/src/components/search/SearchResultsListItem.scss
  packages/frontend/src/components/search/_variables.scss
  packages/frontend/src/components/search/constants.js
  packages/frontend/src/components/search/index.js
  packages/frontend/src/components/search/items/BaseSearchItem.js
  packages/frontend/src/components/search/items/BlockSearchItem.js
  packages/frontend/src/components/search/items/DataContractSearchItem.js
  packages/frontend/src/components/search/items/DocumentSearchItem.js
  packages/frontend/src/components/search/items/IdentitySearchItem.js
  packages/frontend/src/components/search/items/LoadingSearchItem.js
  packages/frontend/src/components/search/items/TransactionSearchItem.js
  packages/frontend/src/components/search/items/ValidatorSearchItem.js
  packages/frontend/src/components/search/items/index.js
  packages/frontend/src/components/ui/icons/index.js
  packages/frontend/src/hooks/index.js
  packages/frontend/src/hooks/useDebounce.js
  packages/frontend/src/styles/colors.js
  packages/frontend/src/styles/components/Badge.js
  packages/frontend/src/styles/components/Button.js
  packages/frontend/src/styles/mixins.scss
  packages/frontend/src/util/datetime.js
Labels: frontend

#519 Update api urls in docs
  packages/frontend/src/app/api/content.md
Labels: frontend

#520 Disable Christmas event in BlocksTotal
  packages/frontend/src/components/blocks/BlocksTotal.js
Labels: frontend

#514 Broadcast transaction in hex
  packages/api/README.md
  packages/api/src/controllers/TransactionsController.js
  packages/api/src/routes.js
  packages/frontend/src/app/api/content.md
Labels: backend

#501 Indexer SQL transactions
  packages/api/src/dao/TransactionsDAO.js
  packages/indexer/src/entities/block_header.rs
  packages/indexer/src/entities/data_contract.rs
  packages/indexer/src/entities/document.rs
  packages/indexer/src/entities/identity.rs
  packages/indexer/src/entities/masternode_vote.rs
  packages/indexer/src/entities/transfer.rs
  packages/indexer/src/indexer/index_block.rs
  packages/indexer/src/indexer/mod.rs
  packages/indexer/src/indexer/process_block.rs
  packages/indexer/src/indexer/start.rs
  packages/indexer/src/main.rs
  packages/indexer/src/models/mod.rs
  packages/indexer/src/processor/mod.rs
  packages/indexer/src/processor/psql/dao/blocks.rs
  packages/indexer/src/processor/psql/dao/data_contracts.rs
  packages/indexer/src/processor/psql/dao/documents.rs
  packages/indexer/src/processor/psql/dao/identities.rs
  packages/indexer/src/processor/psql/dao/masternode_votes.rs
  packages/indexer/src/processor/psql/dao/mod.rs
  packages/indexer/src/processor/psql/dao/state_transitions.rs
  packages/indexer/src/processor/psql/dao/transfers.rs
  packages/indexer/src/processor/psql/dao/validators.rs
  packages/indexer/src/processor/psql/handlers/handle_block.rs
  packages/indexer/src/processor/psql/handlers/handle_data_contract.rs
  packages/indexer/src/processor/psql/handlers/handle_documents.rs
  packages/indexer/src/processor/psql/handlers/handle_identity.rs
  packages/indexer/src/processor/psql/handlers/handle_init_chain.rs
  packages/indexer/src/processor/psql/handlers/handle_masternode_vote.rs
  packages/indexer/src/processor/psql/handlers/handle_st.rs
  packages/indexer/src/processor/psql/handlers/handle_validator.rs
  packages/indexer/src/processor/psql/handlers/mod.rs
  packages/indexer/src/processor/psql/mod.rs
  packages/indexer/src/utils.rs
Labels: indexer

#466 Improve identifier component
  packages/frontend/src/app/validator/[hash]/ValidatorPage.scss
  packages/frontend/src/components/blocks/BlockTotalCard.js
  packages/frontend/src/components/blocks/quorum/QuorumMembersListItem.js
  packages/frontend/src/components/blocks/quorum/QuorumMembersListItem.scss
  packages/frontend/src/components/blocks/quorum/_variables.scss
  packages/frontend/src/components/data/Identifier.js
  packages/frontend/src/components/dataContracts/DataContractTotalCard.js
  packages/frontend/src/components/documents/DocumentTotalCard.js
Labels: frontend

#523 Vertical alignment of PublicKeysListItem
  packages/frontend/src/components/publicKeys/PublicKeysListItem.scss
Labels: frontend

#525 Transactions `totalCount` fix and filter by timestamp
  packages/api/README.md
  packages/api/src/controllers/TransactionsController.js
  packages/api/src/dao/TransactionsDAO.js
  packages/api/test/integration/transactions.spec.js
  packages/frontend/src/app/api/content.md
Labels: backend

#518 Fix documentation for decode and some naming fixes
  packages/api/README.md
  packages/api/src/controllers/DocumentsController.js
  packages/api/src/dao/DocumentsDAO.js
  packages/api/src/models/Document.js
  packages/api/src/utils.js
  packages/api/test/integration/documents.spec.js
  packages/api/test/integration/identities.spec.js
  packages/api/test/integration/main.spec.js
  packages/api/test/unit/utils.spec.js
  packages/frontend/src/app/api/content.md
Labels: backend

#529 Rename `identityNonce` in document to `contractNonce`
  packages/api/README.md
  packages/api/src/dao/DocumentsDAO.js
  packages/api/src/models/Document.js
  packages/api/src/utils.js
  packages/api/test/integration/documents.spec.js
  packages/api/test/integration/identities.spec.js
  packages/api/test/integration/main.spec.js
  packages/api/test/unit/utils.spec.js
  packages/frontend/src/app/api/content.md
Labels: backend

#530 Rename identity contract nonce in Identity Updated transition
  packages/api/README.md
  packages/api/src/utils.js
  packages/api/test/unit/utils.spec.js
  packages/frontend/src/app/api/content.md
Labels: backend

#528 Rename nonce fields
  packages/frontend/src/app/transaction/[hash]/TransactionData.js
  packages/frontend/src/components/transactions/TransitionCard.js
Labels: frontend

#535 Bump dashcore-rpc
  packages/indexer/Cargo.lock
  packages/indexer/Cargo.toml
Labels: indexer

#536 Fix transaction status in Search
  packages/frontend/src/components/search/items/TransactionSearchItem.js
Labels: frontend
