Repository pshenmic/platform-explorer, pull requests merged in 2025-02, with the labels that each got.

#452 Improve charts render
  packages/frontend/src/app/validator/[hash]/BlocksChart.js
  packages/frontend/src/app/validator/[hash]/RewardsChart.js
  packages/frontend/src/components/charts/TimeframeMenu.js
  packages/frontend/src/components/charts/TransactionsHistory.js
  packages/frontend/src/components/charts/config.js
  packages/frontend/src/util/Api.js
  packages/frontend/src/util/datetime.js
Labels: frontend

#456 Gas used field for document revisions
  packages/api/README.md
  packages/api/src/controllers/DocumentsController.js
  packages/api/src/dao/DocumentsDAO.js
  packages/api/src/models/Document.js
  packages/api/test/integration/documents.spec.js
  packages/api/test/integration/identities.spec.js
  packages/api/test/integration/main.spec.js
  packages/frontend/src/app/api/content.md
Labels: backend

#453 Data contract transactions and some additional fields
  packages/api/README.md
  packages/api/src/controllers/DataContractsController.js
  packages/api/src/dao/DataContractsDAO.js
  packages/api/src/models/DataContract.js
  packages/api/src/routes.js
  packages/api/src/server.js
  packages/api/test/integration/data.contracts.spec.js
  packages/api/test/integration/identities.spec.js
  packages/api/test/integration/main.spec.js
  packages/frontend/src/app/api/content.md
Labels: backend

#451 Contested Resource API
  packages/api/README.md
  packages/api/src/controllers/ContestedResourcesController.js
  packages/api/src/controllers/MasternodeVotesController.js
  packages/api/src/dao/ContestedResourcesDAO.js
  packages/api/src/dao/EpochDAO.js
  packages/api/src/dao/MasternodeVotesDAO.js
  packages/api/src/enums/ChoiceEnum.js
  packages/api/src/models/ContestedResource.js
  packages/api/src/models/Vote.js
  packages/api/src/routes.js
  packages/api/src/server.js
  packages/api/src/utils.js
  packages/api/test/integration/contested.spec.js
  packages/api/test/integration/votes.spec.js
  packages/frontend/src/app/api/content.md
  packages/indexer/migrations/V13__add_documents.sql
  packages/indexer/migrations/V39__add_identity_aliases.sql
  packages/indexer/migrations/V46__add_masternode_votes.sql
  packages/indexer/migrations/V47__add_prefunded_voting_balance.sql
  packages/indexer/migrations/V49__add_state_transition_hash_index.sql
  packages/indexer/migrations/V50__data_contracts_schema_index.sql
Labels: backend

#458 Documents owner aliases
  packages/api/README.md
  packages/api/src/controllers/DocumentsController.js
  packages/api/src/controllers/MainController.js
  packages/api/src/dao/DocumentsDAO.js
  packages/api/src/dao/IdentitiesDAO.js
  packages/api/src/models/Document.js
  packages/api/test/integration/documents.spec.js
  packages/api/test/integration/main.spec.js
  packages/frontend/src/app/api/content.md
Labels: backend

#461 Update Owner field render
  packages/frontend/src/app/document/[identifier]/Document.js
  packages/frontend/src/components/data/Identifier.js
  packages/frontend/src/components/documents/DocumentsListItem.js
  packages/frontend/src/components/documents/_variables.scss
Labels: frontend

#464 Fix alias render in document info
  packages/frontend/src/app/document/[identifier]/Document.js
Labels: frontend

#463 Fix for Resource Value convertation
  packages/api/src/utils.js
  packages/api/test/unit/utils.spec.js
Labels: backend

#465 Data Contracts document count fix and identities aliases
  packages/api/README.md
  packages/api/src/controllers/MainController.js
  packages/api/src/dao/DataContractsDAO.js
  packages/api/src/models/DataContract.js
  packages/api/test/integration/data.contracts.spec.js
  packages/api/test/integration/main.spec.js
  packages/frontend/src/app/api/content.md
Labels: backend

#447 Improve Datacontract page
  packages/frontend/src/app/dataContract/[identifier]/DataContract.js
  packages/frontend/src/app/dataContract/[identifier]/DataContract.scss
  packages/frontend/src/components/breadcrumbs/Breadcrumbs.js
  packages/frontend/src/components/breadcrumbs/Breadcrumbs.scss
  packages/frontend/src/components/cards/ValueCard.scss
  packages/frontend/src/components/charts/TimeframeMenu.scss
  packages/frontend/src/components/data/CodeBlock.js
  packages/frontend/src/components/data/CreditsBlock.js
  packages/frontend/src/components/data/CreditsBlock.scss
  packages/frontend/src/components/data/Identifier.js
  packages/frontend/src/components/data/Identifier.scss
  packages/frontend/src/components/data/InfoLine.js
  packages/frontend/src/components/data/InfoLine.scss
  packages/frontend/src/components/data/NotActive.js
  packages/frontend/src/components/data/NotActive.scss
  packages/frontend/src/components/data/TimeDelta.js
  packages/frontend/src/components/data/index.js
  packages/frontend/src/components/dataContracts/DataContractDigestCard.js
  packages/frontend/src/components/dataContracts/DataContractDigestCard.scss
  packages/frontend/src/components/dataContracts/DataContractTotalCard.js
  packages/frontend/src/components/dataContracts/DataContractTotalCard.scss
  packages/frontend/src/components/dataContracts/index.js
  packages/frontend/src/components/documents/DocumentsListItem.js
  packages/frontend/src/components/identities/IdentityDigestCard.scss
  packages/frontend/src/components/layout/navbar/Navbar.js
  packages/frontend/src/components/publicKeys/PublicKeysListItem.js
  packages/frontend/src/components/transactions/TransactionsListItem.js
  packages/frontend/src/components/transfers/TransfersListItem.js
  packages/frontend/src/components/ui/containers/PageDataContainer.scss
  packages/frontend/src/components/ui/containers/ValueContainer.scss
  packages/frontend/src/components/ui/icons/index.js
  packages/frontend/src/styles/components/InfoBlock.scss
  packages/frontend/src/styles/mixins.scss
  packages/frontend/src/styles/variables.scss
  packages/frontend/src/util/Api.js
Labels: frontend

#449 Improve document page
  packages/frontend/src/app/document/[identifier]/Document.js
  packages/frontend/src/app/document/[identifier]/Document.scss
  packages/frontend/src/components/breadcrumbs/Breadcrumbs.js
  packages/frontend/src/components/breadcrumbs/Breadcrumbs.scss
  packages/frontend/src/components/data/Identifier.js
  packages/frontend/src/components/data/Identifier.scss
  packages/frontend/src/components/documents/DocumentTotalCard.js
  packages/frontend/src/components/documents/DocumentTotalCard.scss
  packages/frontend/src/components/documents/index.js
  packages/frontend/src/components/documents/revisions/DocumentsRevisionsList.js
  packages/frontend/src/components/documents/revisions/DocumentsRevisionsList.scss
  packages/frontend/src/components/documents/revisions/DocumentsRevisionsListItem.js
  packages/frontend/src/components/documents/revisions/DocumentsRevisionsListItem.scss
  packages/frontend/src/components/documents/revisions/_variables.scss
  packages/frontend/src/components/layout/navbar/Navbar.js
  packages/frontend/src/components/loading/index.js
  packages/frontend/src/styles/mixins.scss
  packages/frontend/src/util/Api.js
Labels: frontend

#459 Order fix for data contract transactions
  packages/api/README.md
  packages/api/src/dao/DataContractsDAO.js
  packages/api/test/integration/data.contracts.spec.js
  packages/frontend/src/app/api/content.md
Labels: backend

#469 Fix empty transactions for data contract
  packages/api/src/dao/DataContractsDAO.js
Labels: backend

#460 Total gas used
  packages/api/README.md
  packages/api/src/dao/DocumentsDAO.js
  packages/api/src/models/Document.js
  packages/api/test/integration/documents.spec.js
  packages/api/test/integration/identities.spec.js
  packages/api/test/integration/main.spec.js
  packages/frontend/src/app/api/content.md
Labels: backend

#472 Add total gas used field on pages
  packages/frontend/src/app/dataContract/[identifier]/DataContract.js
  packages/frontend/src/app/document/[identifier]/Document.js
  packages/frontend/src/components/dataContracts/DataContractTotalCard.js
  packages/frontend/src/components/documents/DocumentTotalCard.js
Labels: frontend

#473 Documents owner structure in Documents by identity
  packages/api/README.md
  packages/api/src/dao/IdentitiesDAO.js
  packages/api/test/integration/identities.spec.js
  packages/frontend/src/app/api/content.md
Labels: backend

#475 Update documents data render
  packages/frontend/src/app/document/[identifier]/Document.js
  packages/frontend/src/components/Errors/index.js
  packages/frontend/src/components/documents/DocumentActionBadge.js
  packages/frontend/src/components/documents/DocumentTotalCard.js
  packages/frontend/src/components/documents/index.js
  packages/frontend/src/components/documents/revisions/DocumentsRevisionsList.js
  packages/frontend/src/components/documents/revisions/DocumentsRevisionsListItem.js
  packages/frontend/src/components/documents/revisions/_variables.scss
  packages/frontend/src/components/transactions/TransitionCard.js
  packages/frontend/src/styles/mixins.scss
Labels: frontend

#462 Contested Documents List API
  packages/api/README.md
  packages/api/src/constants.js
  packages/api/src/controllers/ContestedResourcesController.js
  packages/api/src/dao/ContestedResourcesDAO.js
  packages/api/src/models/ContestedResource.js
  packages/api/src/models/ContestedResourcesStatus.js
  packages/api/src/routes.js
  packages/api/test/integration/contested.spec.js
  packages/frontend/src/app/api/content.md
Labels: backend

#477 Fix tab style
  packages/frontend/src/styles/components/Tabs.js
Labels: frontend

#478 Quorum block height field
  packages/api/src/models/Quorum.js
Labels: backend

#486 Update field title in TransitionCard
  packages/frontend/src/components/transactions/TransitionCard.js
  packages/frontend/src/components/transactions/TransitionCard.scss
Labels: frontend

#474 Documents revisions fix
  packages/api/src/models/Document.js
Labels: backend

#493 Incorrect quorum index calculation
  packages/api/src/controllers/BlocksController.js
Labels: backend

#494 Invalid filter in #493
  packages/api/src/controllers/BlocksController.js
Labels: backend

#495 Document revision increment after purchase
  packages/indexer/src/entities/document.rs
Labels: indexer

#487 API 500 on bad validator host
  packages/api/src/controllers/ValidatorsController.js
Labels: backend

#455 Fix date range picker active range
  packages/frontend/src/components/calendar/DateRangePicker.js
Labels: frontend

#498 Dapi get documents method architecture fix
  packages/api/src/DAPI.js
  packages/api/src/controllers/BlocksController.js
  packages/api/src/controllers/DocumentsController.js
  packages/api/src/controllers/IdentitiesController.js
  packages/api/test/integration/identities.spec.js
Labels: backend

#489 Power Column for Indexer
  packages/api/test/utils/fixtures.js
  packages/indexer/Cargo.lock
  packages/indexer/Cargo.toml
  packages/indexer/migrations/V46__add_masternode_votes.sql
  packages/indexer/src/entities/identity.rs
  packages/indexer/src/entities/masternode_vote.rs
  packages/indexer/src/indexer/mod.rs
  packages/indexer/src/processor/psql/dao/mod.rs
  packages/indexer/src/processor/psql/mod.rs
Labels: indexer
