Repository pshenmic/platform-explorer, pull requests merged in 2025-07, with the labels that each got.

#597 Tokens List
  packages/api/README.md
  packages/api/src/DAPI.js
  packages/api/src/controllers/TokensController.js
  packages/api/src/dao/TokensDAO.js
  packages/api/src/models/Localization.js
  packages/api/src/models/Token.js
  packages/api/src/routes.js
  packages/api/src/server.js
  packages/api/test/integration/tokens.spec.js
  packages/api/test/utils/fixtures.js
  packages/frontend/src/app/api/content.md
  packages/indexer/migrations/V52__tokens.sql
  packages/indexer/src/entities/token_config.rs
  packages/indexer/src/processor/psql/dao/token.rs
  packages/indexer/src/processor/psql/handlers/handle_token_configuration.rs
Labels: indexer, backend

#600 Prefix dpp & data contracts platform modules to git
  packages/indexer/Cargo.lock
  packages/indexer/Cargo.toml
  packages/indexer/Dockerfile
Labels: indexer

#601 Experimental optimization for Blocks and Transactions
  packages/api/data_contracts/dpns.json
  packages/api/src/dao/BlocksDAO.js
  packages/api/src/dao/TransactionsDAO.js
  packages/api/src/utils.js
  packages/api/test/integration/main.spec.js
  packages/api/test/integration/transactions.spec.js
Labels: backend

#602 Experimental optimization improvments and fixes
  packages/api/src/dao/BlocksDAO.js
  packages/api/src/dao/TransactionsDAO.js
Labels: backend

#598 Integration of pshenmic-dpp
  packages/api/package.json
  packages/api/src/DAPI.js
  packages/api/src/controllers/DocumentsController.js
  packages/api/src/controllers/IdentitiesController.js
  packages/api/src/controllers/TransactionsController.js
  packages/api/src/dao/DataContractsDAO.js
  packages/api/src/dao/DocumentsDAO.js
  packages/api/src/dao/IdentitiesDAO.js
  packages/api/src/enums/PoolingEnum.js
  packages/api/src/server.js
  packages/api/src/utils.js
  packages/api/test/unit/utils.spec.js
Labels: backend

#607 Remove drop database step from CI
  .github/workflows/deploy.yml
  package.json
  packages/api/package.json
  packages/data-contract/package.json
  packages/frontend/package.json
  packages/indexer/Cargo.lock
  packages/indexer/Cargo.toml
Labels: indexer, backend

#608 Fix for data contract deserialization
  packages/api/src/utils.js
Labels: backend

#609 Query optimizations
  packages/api/src/controllers/MainController.js
  packages/api/src/dao/BlocksDAO.js
  packages/api/src/dao/ContestedResourcesDAO.js
  packages/api/src/dao/DataContractsDAO.js
  packages/api/src/dao/DocumentsDAO.js
  packages/api/src/dao/MasternodeVotesDAO.js
  packages/api/src/dao/TokensDAO.js
  packages/api/test/integration/blocks.spec.js
  packages/api/test/integration/contested.spec.js
  packages/api/test/integration/data.contracts.spec.js
  packages/api/test/integration/documents.spec.js
  packages/api/test/integration/epochs.spec.js
  packages/api/test/integration/identities.spec.js
  packages/api/test/integration/main.spec.js
  packages/api/test/integration/tokens.spec.js
  packages/api/test/integration/transactions.spec.js
  packages/api/test/integration/validators.spec.js
  packages/api/test/integration/votes.spec.js
  packages/api/test/utils/fixtures.js
  packages/indexer/migrations/V57__add_state_transitions_block_height.sql
  packages/indexer/src/processor/psql/dao/state_transitions.rs
  packages/indexer/src/processor/psql/handlers/handle_block.rs
  packages/indexer/src/processor/psql/handlers/handle_st.rs
Labels: backend

#611 Token by identifier
  packages/api/README.md
  packages/api/package.json
  packages/api/src/DAPI.js
  packages/api/src/controllers/IdentitiesController.js
  packages/api/src/controllers/TokensController.js
  packages/api/src/dao/DataContractsDAO.js
  packages/api/src/dao/TokensDAO.js
  packages/api/src/models/DataContract.js
  packages/api/src/models/Token.js
  packages/api/src/models/TokenTransition.js
  packages/api/src/routes.js
  packages/api/src/utils.js
  packages/api/test/integration/data.contracts.spec.js
  packages/api/test/integration/identities.spec.js
  packages/api/test/integration/main.spec.js
  packages/api/test/integration/tokens.spec.js
  packages/api/test/unit/mocks/token_config_update_transition.json
  packages/api/test/unit/utils.spec.js
  packages/api/test/utils/fixtures.js
  packages/frontend/src/app/api/content.md
  packages/indexer/migrations/V13__add_documents.sql
  packages/indexer/migrations/V14__add_identities.sql
  packages/indexer/migrations/V15__add_transfers.sql
  packages/indexer/migrations/V16__add_data_contract_owner.sql
  packages/indexer/migrations/V17__add_document_owner.sql
  packages/indexer/migrations/V18__move_owners_to_state_transition.sql
  packages/indexer/migrations/V22__add_data_contracts_owner.sql
  packages/indexer/migrations/V23__add_identities_owner.sql
  packages/indexer/migrations/V24__add_documents_owner.sql
  packages/indexer/migrations/V46__add_masternode_votes.sql
  packages/indexer/migrations/V58__add_tokens_description_and_st_hash.sql
  packages/indexer/src/entities/token_config.rs
  packages/indexer/src/processor/psql/dao/token.rs
  packages/indexer/src/processor/psql/handlers/handle_data_contract.rs
  packages/indexer/src/processor/psql/handlers/handle_token_configuration.rs
Labels: backend

#613 Fix mobile filter menu
  packages/frontend/src/components/filters/Filters.js
  packages/frontend/src/hooks/useFilters.js
Labels: frontend

#612 Add emergency action value in transition card
  packages/frontend/src/components/tokens/TokenEmergencyActionBadge.js
  packages/frontend/src/components/tokens/TokenEmergencyActionBadge.scss
  packages/frontend/src/components/tokens/TokenTransitionCard.js
  packages/frontend/src/components/ui/icons/index.js
Labels: frontend

#618 Tokens rating
  packages/api/README.md
  packages/api/src/controllers/TokensController.js
  packages/api/src/dao/TokensDAO.js
  packages/api/src/routes.js
  packages/api/test/integration/tokens.spec.js
  packages/frontend/src/app/api/content.md
Labels: backend

#620 Tokens rating `timestamp_start` and `timestamp_end`
  packages/api/README.md
  packages/api/src/controllers/TokensController.js
  packages/api/src/dao/TokensDAO.js
  packages/api/test/integration/tokens.spec.js
  packages/frontend/src/app/api/content.md
Labels: backend

#617 Token transitions in Data Contract transitions
  packages/api/README.md
  packages/api/src/dao/DataContractsDAO.js
  packages/api/src/models/DataContract.js
  packages/api/src/utils.js
  packages/api/test/integration/data.contracts.spec.js
  packages/api/test/unit/utils.spec.js
  packages/api/test/utils/drop.js
  packages/api/test/utils/fixtures.js
  packages/frontend/src/app/api/content.md
  packages/indexer/migrations/V59__add_tokens_names.sql
  packages/indexer/migrations/V60__add_data_contract_transitions.sql
  packages/indexer/src/entities/token_config.rs
  packages/indexer/src/enums/batch_type.rs
  packages/indexer/src/processor/psql/dao/data_contracts.rs
  packages/indexer/src/processor/psql/dao/state_transitions.rs
  packages/indexer/src/processor/psql/dao/token.rs
  packages/indexer/src/processor/psql/handlers/handle_batch.rs
  packages/indexer/src/processor/psql/handlers/handle_block.rs
  packages/indexer/src/processor/psql/handlers/handle_data_contract.rs
  packages/indexer/src/processor/psql/handlers/handle_documents.rs
  packages/indexer/src/processor/psql/handlers/handle_st.rs
  packages/indexer/src/processor/psql/handlers/handle_token_configuration.rs
  packages/indexer/src/processor/psql/handlers/handle_tokens.rs
  packages/indexer/src/processor/psql/handlers/mod.rs
  packages/indexer/src/processor/psql/mod.rs
Labels: indexer, backend

#614 Improve transactions list
  packages/frontend/src/app/dataContract/[identifier]/DataContract.js
  packages/frontend/src/app/transaction/[hash]/TransactionData.js
  packages/frontend/src/app/transaction/[hash]/TransactionPage.js
  packages/frontend/src/components/transactions/BatchTypeBadge.js
  packages/frontend/src/components/transactions/TransactionsFilter.js
  packages/frontend/src/components/transactions/TransactionsListItem.js
  packages/frontend/src/components/transactions/index.js
  packages/frontend/src/enums/documentAction.js
  packages/frontend/src/enums/state.transition.type.js
  packages/frontend/src/enums/tokenTransition.js
Labels: frontend

#623 Transaction types in string
  packages/api/README.md
  packages/api/src/controllers/IdentitiesController.js
  packages/api/src/controllers/TransactionsController.js
  packages/api/src/dao/BlocksDAO.js
  packages/api/src/dao/DataContractsDAO.js
  packages/api/src/dao/IdentitiesDAO.js
  packages/api/src/dao/TransactionsDAO.js
  packages/api/src/enums/StateTransitionEnum.js
  packages/api/src/schemas.js
  packages/api/test/integration/data.contracts.spec.js
  packages/api/test/integration/identities.spec.js
  packages/api/test/integration/main.spec.js
  packages/api/test/integration/transactions.spec.js
  packages/api/test/unit/utils.spec.js
  packages/frontend/src/app/api/content.md
Labels: backend

#624 Batch type filter for transactions list
  packages/api/README.md
  packages/api/src/controllers/TransactionsController.js
  packages/api/src/dao/TransactionsDAO.js
  packages/api/src/schemas.js
  packages/api/test/integration/transactions.spec.js
  packages/frontend/src/app/api/content.md
  packages/indexer/migrations/V61__fix_batch_type.sql
  packages/indexer/src/processor/psql/dao/state_transitions.rs
Labels: backend

#625 Update transactions types format on the frontend
  packages/frontend/src/app/transaction/[hash]/TransactionData.js
  packages/frontend/src/app/transaction/[hash]/TransactionPage.js
  packages/frontend/src/components/transactions/TransactionsFilter.js
  packages/frontend/src/components/transactions/TransactionsListItem.js
  packages/frontend/src/components/transactions/TypeBadge.js
  packages/frontend/src/components/transfers/TypeBadge.js
  packages/frontend/src/enums/state.transition.type.js
  packages/frontend/src/util/index.js
Labels: frontend
